### ISSUE TITLE
IGDB v4 support

### ISSUE THREAD

**Issue by ArtemGulia** [twitchtv/igdb-api-python#3]
Will this library be updated to support new IGDB API version?
https://api-docs.igdb.com/#upgrading-to-v4-from-v3

**Comment by dustyjewett** [comment]
@ArtemGulia: It's coming, our python guy is deep in his thesis, so I'm waiting for him to surface and review my code.

**Comment by dustyjewett** [comment]
We've updated the package, and since the api version was in the name, the new package name is `igdb-api-v4`. Please let us know, either here or on discord, if you have any issues.
